"""baseline_schema

全量基线迁移 — 在全新数据库上创建除渠道表之外的所有业务表。
渠道表(channel_*)与 users.is_shadow 由后续迁移 6fea3105d1cf 添加。

Revision ID: 2d4c93e50bae
Revises:
Create Date: 2026-08-01 16:26:46.717763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d4c93e50bae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 扩展：uuid 生成与 pg_trgm 文本相似度检索（连接层也会兜底创建）
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_knowledge_bases',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='智能体ID'),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False, comment='知识库ID'),
    sa.PrimaryKeyConstraint('agent_id', 'knowledge_base_id'),
    comment='智能体-知识库关联表'
    )
    op.create_index('idx_agent_knowledge_bases_agent', 'agent_knowledge_bases', ['agent_id'], unique=False)
    op.create_index('idx_agent_knowledge_bases_kb', 'agent_knowledge_bases', ['knowledge_base_id'], unique=False)
    op.create_table('agent_relationships',
    sa.Column('parent_id', sa.UUID(), nullable=False, comment='主控智能体ID'),
    sa.Column('child_id', sa.UUID(), nullable=False, comment='子智能体ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id'),
    comment='智能体层级关系表（多对多）'
    )
    op.create_index('idx_agent_rel_child', 'agent_relationships', ['child_id'], unique=False)
    op.create_index('idx_agent_rel_parent', 'agent_relationships', ['parent_id'], unique=False)
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='智能体ID'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='技能ID'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id'),
    comment='智能体-技能关联表'
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='关联智能体ID'),
    sa.Column('version', sa.String(length=64), nullable=False, comment='版本号'),
    sa.Column('changelog', sa.Text(), nullable=True, comment='版本说明'),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='发布时的配置快照(JSON)'),
    sa.Column('published_by', sa.UUID(), nullable=True, comment='发布者用户ID'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='发布时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前生效版本'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能体版本表'
    )
    op.create_index('idx_agent_versions_active', 'agent_versions', ['agent_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_agent_versions_agent', 'agent_versions', ['agent_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='所属租户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='智能体名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('icon', sa.String(length=64), nullable=False, comment='图标标识'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('model_id', sa.UUID(), nullable=True, comment='关联LLM模型ID'),
    sa.Column('enabled_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='启用的工具列表(JSON)'),
    sa.Column('mcp_server_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='绑定的MCP服务器ID列表(JSON)'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='推理温度(0.0-2.0)，为空时使用全局默认值'),
    sa.Column('max_iterations', sa.Integer(), nullable=True, comment='ReAct 最大迭代次数(1-100)，为空时使用全局默认值'),
    sa.Column('welcome_message', sa.Text(), nullable=True, comment='欢迎语，新会话开始时展示'),
    sa.Column('starter_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='快捷提问列表，在欢迎页展示引导用户开始对话'),
    sa.Column('enable_memory_extraction', sa.Boolean(), nullable=False, comment='是否启用自动记忆提取'),
    sa.Column('enable_retry', sa.Boolean(), nullable=False, comment='LLM API 调用失败时是否自动重试'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建者用户ID'),
    sa.Column('visibility', sa.String(length=16), server_default='tenant', nullable=False, comment='可见范围: tenant/private'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能体表'
    )
    op.create_index('idx_agents_creator', 'agents', ['created_by'], unique=False)
    op.create_index('idx_agents_tenant_visibility', 'agents', ['tenant_id', 'visibility'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型'),
    sa.Column('resource', sa.String(length=256), nullable=True, comment='操作资源'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='操作详情(JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='审计日志表'
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('cron_jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('agent_id', sa.UUID(), nullable=True, comment='关联智能体ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='任务名称'),
    sa.Column('cron_expr', sa.String(length=128), nullable=True, comment='Cron表达式'),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True, comment='单次执行时间'),
    sa.Column('message', sa.Text(), nullable=True, comment='发送给智能体的消息'),
    sa.Column('task_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='任务配置(JSON)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='最后执行时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务表'
    )
    op.create_table('delegations',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('parent_session_id', sa.UUID(), nullable=False, comment='父级会话ID'),
    sa.Column('parent_agent_id', sa.UUID(), nullable=False, comment='发起委派的主控智能体ID'),
    sa.Column('child_agent_id', sa.UUID(), nullable=False, comment='被委派的子智能体ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('depth', sa.Integer(), nullable=False, comment='委派深度'),
    sa.Column('task', sa.Text(), nullable=False, comment='委派任务描述'),
    sa.Column('context', sa.Text(), nullable=True, comment='额外上下文'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: pending/running/completed/failed/timeout'),
    sa.Column('result', sa.Text(), nullable=True, comment='子智能体最终输出'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='令牌用量'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='执行耗时(毫秒)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能体委派执行记录表'
    )
    op.create_index('idx_delegations_session', 'delegations', ['parent_session_id', 'depth'], unique=False)
    op.create_index('idx_delegations_status', 'delegations', ['status'], unique=False)
    op.create_index('idx_delegations_user', 'delegations', ['user_id', 'created_at'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='所属租户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='知识库名称'),
    sa.Column('dataset_id', sa.String(length=256), nullable=False, comment='RAGFlow dataset ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建者用户ID'),
    sa.Column('visibility', sa.String(length=16), server_default='tenant', nullable=False, comment='可见范围: tenant/private'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库表'
    )
    op.create_index('idx_knowledge_bases_dataset_id', 'knowledge_bases', ['dataset_id'], unique=False)
    op.create_index('idx_knowledge_bases_tenant_visibility', 'knowledge_bases', ['tenant_id', 'visibility'], unique=False)
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('provider_id', sa.UUID(), nullable=False, comment='关联提供商ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='显示名称'),
    sa.Column('model_name', sa.String(length=256), nullable=False, comment='模型标识符'),
    sa.Column('is_multimodal', sa.Boolean(), server_default='false', nullable=False, comment='是否为多模态模型(支持图片输入)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认模型'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='LLM模型表'
    )
    op.create_index('idx_llm_models_default', 'llm_models', ['is_default'], unique=False, postgresql_where=sa.text('true'))
    op.create_table('llm_providers',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='显示名称'),
    sa.Column('provider_type', sa.String(length=32), nullable=False, comment='提供商类型: openai/anthropic'),
    sa.Column('base_url', sa.String(length=512), nullable=True, comment='API基础地址'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True, comment='加密后的API密钥'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='LLM提供商表'
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='显示名称'),
    sa.Column('transport_type', sa.String(length=32), nullable=False, comment='传输类型: sse/streamable-http'),
    sa.Column('url', sa.String(length=512), nullable=False, comment='服务端点 URL'),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='HTTP 请求头'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('tool_prefix', sa.String(length=32), nullable=True, comment='工具名称前缀 (避免冲突)'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='调用超时 (秒)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='连接状态: connected/disconnected/error'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='最后错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='MCP 服务器配置表'
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('layer', sa.String(length=4), nullable=False, comment='记忆层级: L1/L2/L3'),
    sa.Column('content', sa.Text(), nullable=False, comment='记忆内容'),
    sa.Column('search_vec', sa.Text(), nullable=True, comment='搜索向量(用于pg_trgm检索)'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='元数据(JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='记忆表'
    )
    op.create_index('idx_memories_user_layer', 'memories', ['user_id', 'layer', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='关联会话ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='消息角色: user/assistant/system/tool'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用信息(JSON)'),
    sa.Column('tool_call_id', sa.String(length=128), nullable=True, comment='工具调用ID'),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='令牌用量统计(JSON)'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='图片附件元数据: [{key, url, mime, size, filename}]'),
    sa.Column('file_attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='文件附件元数据: [{file_id, filename, mime, size, workspace_path}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='消息表'
    )
    op.create_index('idx_messages_session', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('portrait_versions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='画像内容快照'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='来源: manual/ai'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='个人画像历史版本表'
    )
    op.create_index('idx_portrait_versions_user', 'portrait_versions', ['user_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='令牌哈希值'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    comment='刷新令牌表'
    )
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('remote_tools',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='工具名称 (function name 规范)'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='显示名称 (中文友好)'),
    sa.Column('description', sa.Text(), nullable=False, comment='工具描述 (LLM 可见)'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 方法: GET/POST/PUT/DELETE/PATCH'),
    sa.Column('url_template', sa.String(length=1024), nullable=False, comment='URL 模板'),
    sa.Column('parameters_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema 参数定义'),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='静态请求头 (不含认证)'),
    sa.Column('auth_type', sa.String(length=32), nullable=False, comment='认证类型: none/bearer/api_key/basic/custom_header'),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='认证配置'),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Query 参数映射'),
    sa.Column('body_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求体模板'),
    sa.Column('response_extract', sa.String(length=256), nullable=True, comment='响应 JSONPath 提取'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间 (秒)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='自定义远程工具配置表'
    )
    op.create_index('idx_remote_tools_active', 'remote_tools', ['is_active'], unique=False)
    op.create_index('idx_remote_tools_name', 'remote_tools', ['name'], unique=False)
    op.create_table('sandbox_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='关联会话ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=True, comment='关联工作区ID'),
    sa.Column('container_id', sa.String(length=128), nullable=True, comment='容器ID'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: active/destroyed'),
    sa.Column('cpu_peak', sa.Numeric(precision=10, scale=4), nullable=False, comment='CPU峰值使用率'),
    sa.Column('memory_peak_mb', sa.Integer(), nullable=False, comment='内存峰值(MB)'),
    sa.Column('command_count', sa.Integer(), nullable=False, comment='命令执行次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True, comment='销毁时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='沙箱会话表'
    )
    op.create_index('idx_sandbox_active', 'sandbox_sessions', ['status'], unique=False)
    op.create_index('idx_sandbox_user', 'sandbox_sessions', ['user_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('agent_id', sa.UUID(), nullable=True, comment='关联智能体ID'),
    sa.Column('workspace_id', sa.UUID(), nullable=True, comment='关联工作区ID'),
    sa.Column('title', sa.String(length=512), nullable=True, comment='会话标题'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='是否归档'),
    sa.Column('context_summary', sa.Text(), nullable=True, comment='对话历史摘要(L4 工作记忆压缩)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='会话表'
    )
    op.create_index('idx_sessions_user', 'sessions', ['user_id', 'updated_at'], unique=False)
    op.create_table('skill_versions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='关联技能ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='版本内容'),
    sa.Column('object_key', sa.String(length=512), nullable=True, comment='MinIO对象存储键'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='技能版本历史表'
    )
    op.create_index('idx_skill_versions', 'skill_versions', ['skill_id', 'version'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='技能名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='技能描述'),
    sa.Column('content', sa.Text(), nullable=True, comment='技能内容'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='标签列表(JSON)'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='分类'),
    sa.Column('trigger_condition', sa.Text(), nullable=True, comment='触发条件'),
    sa.Column('use_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功次数'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('execution_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='执行日志(JSON)'),
    sa.Column('scripts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='脚本文件清单(已弃用, 使用 files): [{path, description, language}]'),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='文件清单: [{path, type, description, language, size}]'),
    sa.Column('object_key', sa.String(length=512), nullable=True, comment='MinIO对象存储键'),
    sa.Column('search_vec', sa.Text(), nullable=True, comment='搜索向量(用于pg_trgm检索)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='技能表'
    )
    op.create_index('idx_skills_user', 'skills', ['user_id', 'category', 'is_active'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=128), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('key'),
    comment='系统全局配置表'
    )
    op.create_table('tenant_memberships',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='加入时间'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id'),
    comment='租户用户成员关系表'
    )
    op.create_index('idx_tenant_memberships_user', 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='租户唯一标识'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='租户表'
    )
    op.create_table('token_usage_daily',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('model', sa.String(length=128), nullable=False, comment='模型名称'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='提示令牌数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='补全令牌数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总令牌数'),
    sa.Column('request_count', sa.Integer(), nullable=False, comment='请求次数'),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False, comment='费用(美元)'),
    sa.PrimaryKeyConstraint('user_id', 'date', 'model'),
    comment='每日令牌用量统计表'
    )
    op.create_index('idx_token_usage_user_date', 'token_usage_daily', ['user_id', 'date'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='关联会话ID'),
    sa.Column('input', sa.Text(), nullable=True, comment='输入内容'),
    sa.Column('output', sa.Text(), nullable=True, comment='输出内容'),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='执行步骤(JSON)'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总令牌数'),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=False, comment='执行耗时(毫秒)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='执行追踪表'
    )
    op.create_index('idx_traces_user', 'traces', ['user_id', 'created_at'], unique=False)
    op.create_table('user_configs',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('trust_level', sa.String(length=32), nullable=False, comment='信任级别'),
    sa.Column('memory_top_k', sa.Integer(), nullable=False, comment='记忆检索数量'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='扩展配置(JSON)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='用户配置表'
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='显示名称'),
    sa.Column('personal_portrait', sa.Text(), nullable=True, comment='个人画像 Markdown'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    comment='用户档案表'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱地址'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='所属租户ID'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='角色: user/admin/superadmin'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='用户表'
    )
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='工作区显示名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='URL友好标识(用户内唯一)'),
    sa.Column('description', sa.Text(), nullable=True, comment='工作区描述'),
    sa.Column('file_count', sa.Integer(), nullable=False, comment='文件数量(冗余)'),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False, comment='总大小(字节, 冗余)'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='最后同步时间'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认工作区'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_workspace_user_slug'),
    comment='工作区表'
    )
    op.create_index('idx_workspaces_user', 'workspaces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspaces_user', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_table('user_configs')
    op.drop_index('idx_traces_user', table_name='traces')
    op.drop_table('traces')
    op.drop_index('idx_token_usage_user_date', table_name='token_usage_daily')
    op.drop_table('token_usage_daily')
    op.drop_table('tenants')
    op.drop_index('idx_tenant_memberships_user', table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_table('system_config')
    op.drop_index('idx_skills_user', table_name='skills')
    op.drop_table('skills')
    op.drop_index('idx_skill_versions', table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_sandbox_user', table_name='sandbox_sessions')
    op.drop_index('idx_sandbox_active', table_name='sandbox_sessions')
    op.drop_table('sandbox_sessions')
    op.drop_index('idx_remote_tools_name', table_name='remote_tools')
    op.drop_index('idx_remote_tools_active', table_name='remote_tools')
    op.drop_table('remote_tools')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_portrait_versions_user', table_name='portrait_versions')
    op.drop_table('portrait_versions')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_memories_user_layer', table_name='memories')
    op.drop_table('memories')
    op.drop_table('mcp_servers')
    op.drop_table('llm_providers')
    op.drop_index('idx_llm_models_default', table_name='llm_models', postgresql_where=sa.text('true'))
    op.drop_table('llm_models')
    op.drop_index('idx_knowledge_bases_tenant_visibility', table_name='knowledge_bases')
    op.drop_index('idx_knowledge_bases_dataset_id', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('idx_delegations_user', table_name='delegations')
    op.drop_index('idx_delegations_status', table_name='delegations')
    op.drop_index('idx_delegations_session', table_name='delegations')
    op.drop_table('delegations')
    op.drop_table('cron_jobs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_agents_tenant_visibility', table_name='agents')
    op.drop_index('idx_agents_creator', table_name='agents')
    op.drop_table('agents')
    op.drop_index('idx_agent_versions_agent', table_name='agent_versions')
    op.drop_index('idx_agent_versions_active', table_name='agent_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_table('agent_versions')
    op.drop_table('agent_skills')
    op.drop_index('idx_agent_rel_parent', table_name='agent_relationships')
    op.drop_index('idx_agent_rel_child', table_name='agent_relationships')
    op.drop_table('agent_relationships')
    op.drop_index('idx_agent_knowledge_bases_kb', table_name='agent_knowledge_bases')
    op.drop_index('idx_agent_knowledge_bases_agent', table_name='agent_knowledge_bases')
    op.drop_table('agent_knowledge_bases')
    # ### end Alembic commands ###
